[package]
name = "milkmilk"
version = "0.0.1"
edition = "2021"
default-run="mkmk"

[[bin]]
name = "mkmk"
path = "src/main.rs"
edition = "2021"


[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
serde = { version = "1.0.157", features = ["derive"] }
serde_json = "1.0.94"
 